keypointnet:
    n_keypoints: 8
    bottleneck_dimension: 128
    backbone: "resnet_34"
    debug: True
    debug_path: ""

loss:
    multiview_consistency: 1.0
    separation: 1.0
    silhouette: 1.0
    pose: 1.0

    reduction: "mean"
    margin: 10

optimizer:
    name: Adam
    learning_rate: 1e-3
    enable_schedule: True
    schedular_step_size: 5000
    gamma: 0.99
    weight_decay: 0.0

trainer:
    precision: high 
    model_checkpoint_name: trained_keynet_d64
    epochs: 2500
    enable_logging: True
    tensorboard_path: /tmp
    training_directory: /tmp
    enable_checkpointing: True
    model_path: ""
    logging_frequency: 1
    validation_frequency: 10

dataloader:
    rgb_directory: dataset/rgbs
    mask_directory: dataset/masks
    depth_directory: dataset/depths
    extrinsic_directory: dataset/cam_to_world_trafo
    camera_intrinsics_numpy_text: dataset/intrinsics.txt
    random_background_directory: dataset/random_backgrounds

    test_size: 0.2
    shuffle: True

    n_workers: 4
    batch_size: 1

    random_hintergrund_probability: 0.4
    noisy_hintergrund_probability: 0.4
    masked_hintergrund_probability: 0.2

    greyscale_probability: 0.1
    colorjitter_probability: 0.8
    gaussian_blur_probability: 0.1
    
