keypointnet:
    n_keypoints: 8
    bottleneck_dimension: 512
    backbone: "resnet_34"
    debug: False
    debug_path: ""

loss:
    multiview_consistency: 1.0
    spatial_distribution: 0.001
    separation: 1.0
    silhouette: 1.0
    pose: 0.2

    reduction: "mean"
    margin: 2

optimizer:
    name: Adam
    learning_rate: 1e-3
    enable_schedule: False
    schedular_step_size: 4000
    gamma: 0.9
    weight_decay: 0.0

trainer:
    precision: high 
    model_checkpoint_name: trained_keynet
    epochs: 2500
    enable_logging: True
    tensorboard_path: /tmp
    training_directory: /tmp
    enable_checkpointing: True
    model_path: /tmp
    logging_frequency: 1
    validation_frequency: 10

dataloader:
    directory: dataset/dataset
    depth_ratio: 1

    test_size: 0.1
    shuffle: True

    n_workers: 60
    batch_size: 8

    random_hintergrund_probability: 0.4
    noisy_hintergrund_probability: 0.4
    masked_hintergrund_probability: 0.2

    greyscale_probability: 0.1
    colorjitter_probability: 0.8
    gaussian_blur_probability: 0.1
