don:
    descriptor_dimension: 6
    backbone: resnet_34
    n_correspondence: 64
    debug: True
    debug_path: ""

optimizer:
    name: Adam
    learning_rate: 3e-4
    enable_schedule: True
    schedular_step_size: 2000
    gamma: 0.9
    weight_decay: 1e-4

loss:
    name: pixelwise_ntxent_loss
    reduction: mean
    temperature: 0.1

trainer:
    precision: high 
    model_checkpoint_name: trained_don
    epochs: 500
    enable_logging: True
    tensorboard_path: /tmp
    training_directory: /tmp
    enable_checkpointing: True
    model_path: /tmp
    logging_frequency: 1
    validation_frequency: 1

dataloader:
    rgb_directory: dataset/rgbs
    mask_directory: dataset/masks
    random_background_directory: dataset/random_backgrounds

    test_size: 0.2
    shuffle: True

    n_workers: 10
    batch_size: 1

    random_hintergrund_probability: 0.4
    noisy_hintergrund_probability: 0.4
    masked_hintergrund_probability: 0.2

    greyscale_probability: 0.1
    colorjitter_probability: 0.8
    gaussian_blur_probability: 0.1
    
