don:
    descriptor_dimension: 3
    backbone: "resnet_34"
    n_correspondence: 100

optimizer:
    name: Adam
    learning_rate: 3e-5
    enable_schedular: False
    schedular_step_size: 1e-1

loss:
    name: pixelwise_correspondence_loss
    reduction: mean
    temperature: 0.1

trainer:
    model_checkpoint_name: dense_mf
    epochs: 500
    enable_logging: True
    tensorboard_path: sandbox/don/tensorboard
    training_directory: sandbox/don/training
    enable_checkpointing: True
    model_path: sandbox/don/trained_model
    logging_frequency: 1
    validation_frequency: 1

dataloader:
    directory: dataset/dataset
    depth_ratio: 1

    test_size: 0.1
    shuffle: True

    n_workers: 10
    batch_size: 1
    