don:
    descriptor_dimension: 3
    backbone: resnet_34
    n_correspondence: 50
    debug: True
    debug_path: ""

optimizer:
    name: Adam
    learning_rate: 3e-4
    enable_schedule: False
    schedular_step_size: 2000
    gamma: 0.9
    weight_decay: 1e-4

loss:
    name: pixelwise_correspondence_loss
    reduction: mean
    temperature: 0.1

trainer:
    model_checkpoint_name: dense_mf
    epochs: 500
    enable_logging: True
    tensorboard_path: /tmp
    training_directory: /tmp
    enable_checkpointing: True
    model_path: /tmp
    logging_frequency: 1
    validation_frequency: 1

dataloader:
    directory: dataset/dataset
    depth_ratio: 1

    test_size: 0.1
    shuffle: True

    n_workers: 10
    batch_size: 2

    random_hintergrund_probability: 0.4
    noisy_hintergrund_probability: 0.4
    masked_hintergrund_probability: 0.2

    greyscale_probability: 0.1
    colorjitter_probability: 0.8
    gaussian_blur_probability: 0.1
    